-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.pessoas
(
    "id_Pessoa" integer NOT NULL,
    "nome_Pessoa" text NOT NULL,
    "email_Pessoa" text NOT NULL,
    "tel_Pessoa" text NOT NULL,
    "senha_Pessoa" text NOT NULL,
    PRIMARY KEY ("id_Pessoa")
);

CREATE TABLE IF NOT EXISTS public.produtos
(
    "id_Produto" integer NOT NULL,
    "nome_Produto" text NOT NULL,
    "vlrCompra_Produto" money NOT NULL,
    "vlrVenda_Produto" money NOT NULL,
    "qtd_Produto" integer NOT NULL,
    PRIMARY KEY ("id_Produto")
);

CREATE TABLE IF NOT EXISTS public.vendas
(
    "id_Venda" integer NOT NULL,
    "id_Pessoa" integer NOT NULL,
    "data_Venda" date NOT NULL,
    "pgto_Venda" text NOT NULL,
    "vlrTotal_Venda" money NOT NULL,
    PRIMARY KEY ("id_Venda")
);

CREATE TABLE IF NOT EXISTS public.vendas_itens
(
    "id_venda_Itens" integer NOT NULL,
    "id_Venda" integer NOT NULL,
    "id_Produtos" integer NOT NULL
);

ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT "Pessoa_Venda" FOREIGN KEY ("id_Pessoa")
    REFERENCES public.pessoas ("id_Pessoa") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas_itens
    ADD CONSTRAINT "venda_itensVenda" FOREIGN KEY ("id_Venda")
    REFERENCES public.vendas ("id_Venda") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas_itens
    ADD CONSTRAINT "produto_itensVenda" FOREIGN KEY ("id_Produtos")
    REFERENCES public.produtos ("id_Produto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;